/*
 * JSON message class to be displayed.
 *
 * This class was generated by jsonschema2pojo.
 */
package Classes;

import Classes.Parser.Line;
import javax.annotation.Generated;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;

@Generated("org.jsonschema2pojo")
public class Message
{

    @SerializedName("bt")
    @Expose
    private Integer bt;
    @SerializedName("head")
    @Expose
    private Head head;
    @SerializedName("vmms")
    @Expose
    private Vmms vmms;
    @SerializedName("if")
    @Expose
    private Inf inf;
    @SerializedName("eng")
    @Expose
    private Eng eng;
    @SerializedName("sys")
    @Expose
    private Sys sys;

    /**
     * No args constructor for use in serialisation
     */
    public Message()
    {
    }

    /**
     * @param bt Block type number.
     * @param head Message header object.
     * @param vmms Vessel motion monitor system object.
     * @param inf Intelligent Fender object. (inf used as if is reserved.)
     * @param eng Engine object.
     * @param sys System voltage and temperature object.
     */
    public Message(Integer bt, Head head, Vmms vmms, Inf inf, Eng eng, Sys sys)
    {
        this.bt = bt;
        this.head = head;
        this.vmms = vmms;
        this.inf = inf;
        this.eng = eng;
        this.sys = sys;
    }

    public Message(Line line, int vid, double[] hve, double[] pit, double[] rol, double[] hed, double[] ax, double[] ay, double[] az)
    {
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss.sss");
	Date date = new Date();
	
        
        this.bt = 257;
        this.head = new Head(vid, dateFormat.format(date), line.getLatitude(), line.getLongitude(), 0, 0.0f, 257);
        /*
         double[] hve,
         double[] pit,
         double[] rol,
         double[] hed,
         Double hrms,
         Double prms,
         Double rrms,
         double[] ax,
         double[] ay,
         double[] az
         */
        //Need to get the arrays set up....
        this.vmms = new Vmms(hve, pit, rol, hed, ax, ay, az);
        /*
         Float pax, Float pay, Float paz, 
         Float pbx, Float pby, Float pbz, 
         Float pcx, Float pcy, Float pcz, 
         Float pdx, Float pdy, Float pdz
         */
        this.inf = new Inf(0.0f, 0.0f, 0.0f, 0.0f,
                0.0f, 0.0f, 0.0f, 0.0f,
                0.0f, 0.0f, 0.0f, 0.0f);
        /*
         Double fca, Double fcb, 
         Integer rpma, Integer rpmb, 
         Integer tha, Integer thb
         */
        this.eng = new Eng(0.0, 0.0, 0, 0, 0, 0);
        /*
         Double volt, Double temp
         */
        this.sys = new Sys(0.0, 0.0);
    }

    /**
     * Get the block type for this message.
     *
     * @return The bt (block type) for this message.
     */
    public Integer getBt()
    {
        return bt;
    }

    /**
     * Set the block type for this message.
     *
     * @param bt The bt (block type) for this message.
     */
    public void setBt(Integer bt)
    {
        this.bt = bt;
    }

    /**
     * Get the header for this message.
     *
     * @return The head (header) for this message.
     */
    public Head getHead()
    {
        return head;
    }

    /**
     * Set the header for this message.
     *
     * @param head The head (header) for this message.
     */
    public void setHead(Head head)
    {
        this.head = head;
    }

    /**
     * Get the vessel motion monitoring system object for this message.
     *
     * @return The vmms (vessel motion monitoring system) for this message.
     */
    public Vmms getVmms()
    {
        return vmms;
    }

    /**
     * Set the vessel motion monitoring system object for this message.
     *
     * @param vmms The vmms (vessel motion monitoring system) for this message.
     */
    public void setVmms(Vmms vmms)
    {
        this.vmms = vmms;
    }

    /**
     * Get the intelligent fender object for this message.
     *
     * @return The inf (intelligent fender) object for this message.
     */
    public Inf getInf()
    {
        return inf;
    }

    /**
     * Set the intelligent fender object for this message.
     *
     * @param inf The if (intelligent fender) object for this message.
     */
    public void setInf(Inf inf)
    {
        this.inf = inf;
    }

    /**
     * Get the engine object for this message.
     *
     * @return The eng (engine) object for this message.
     */
    public Eng getEng()
    {
        return eng;
    }

    /**
     * Set the engine object for this message.
     *
     * @param eng The eng (engine) object for this message.
     */
    public void setEng(Eng eng)
    {
        this.eng = eng;
    }

    /**
     * Get the system object for this message.
     *
     * @return The sys (system) object for this message.
     */
    public Sys getSys()
    {
        return sys;
    }

    /**
     * Set the system object for this message.
     *
     * @param sys The sys (system) object for this message.
     */
    public void setSys(Sys sys)
    {
        this.sys = sys;
    }

    /**
     * Engine class.
     *
     * Contains engine details.
     */
    @Generated("org.jsonschema2pojo")
    public class Eng
    {

        @SerializedName("fca")
        @Expose
        private Double fca;
        @SerializedName("fcb")
        @Expose
        private Double fcb;
        @SerializedName("rpma")
        @Expose
        private Integer rpma;
        @SerializedName("rpmb")
        @Expose
        private Integer rpmb;
        @SerializedName("tha")
        @Expose
        private Integer tha;
        @SerializedName("thb")
        @Expose
        private Integer thb;

        /**
         * No args constructor for use in serialisation
         */
        public Eng()
        {
        }

        /**
         * @param fca Fuel consumption for engine A.
         * @param fcb Fuel consumption for engine B.
         * @param rpma RPM for engine A.
         * @param rpmb RPM for engine B.
         * @param tha Throttle percentage for engine A.
         * @param thb Throttle percentage for engine B.
         */
        public Eng(Double fca, Double fcb, Integer rpma, Integer rpmb, Integer tha, Integer thb)
        {
            this.fca = fca;
            this.fcb = fcb;
            this.rpma = rpma;
            this.rpmb = rpmb;
            this.tha = tha;
            this.thb = thb;
        }

        /**
         * Get the fuel consumption for engine A.
         *
         * @return The fca (fuel consumption) for engine A.
         */
        public Double getFca()
        {
            return fca;
        }

        /**
         * Set the fuel consumption for engine B.
         *
         * @param fca The fca (fuel consumption) for engine A.
         */
        public void setFca(Double fca)
        {
            this.fca = fca;
        }

        /**
         * Get the fuel consumption for engine A.
         *
         * @return The fcb (fuel consumption) for engine B.
         */
        public Double getFcb()
        {
            return fcb;
        }

        /**
         * Set the fuel consumption for engine A.
         *
         * @param fcb The fcb (fuel consumption) for engine B.
         */
        public void setFcb(Double fcb)
        {
            this.fcb = fcb;
        }

        /**
         * Get the RPM for engine A.
         *
         * @return The rpma (RPM) for engine A.
         */
        public Integer getRpma()
        {
            return rpma;
        }

        /**
         * Set the RPM for engine A.
         *
         * @param rpma The rpma (RPM) for engine A.
         */
        public void setRpma(Integer rpma)
        {
            this.rpma = rpma;
        }

        /**
         * Get the RPM for engine B.
         *
         * @return The rpmb (RPM) for engine B.
         */
        public Integer getRpmb()
        {
            return rpmb;
        }

        /**
         * Set the RPM for engine B.
         *
         * @param rpmb The rpmb (RPM) for engine B.
         */
        public void setRpmb(Integer rpmb)
        {
            this.rpmb = rpmb;
        }

        /**
         * Get the throttle percentage for engine A.
         *
         * @return The tha (throttle percentage) for engine A.
         */
        public Integer getTha()
        {
            return tha;
        }

        /**
         * Set the throttle percentage for engine A.
         *
         * @param tha The tha (throttle percentage) for engine A.
         */
        public void setTha(Integer tha)
        {
            this.tha = tha;
        }

        /**
         * Get the throttle percentage for engine B.
         *
         * @return The thb (throttle percentage) for engine B.
         */
        public Integer getThb()
        {
            return thb;
        }

        /**
         * Set the throttle percentage for engine B.
         *
         * @param thb The thb (throttle percentage) for engine B.
         */
        public void setThb(Integer thb)
        {
            this.thb = thb;
        }
    }

    /**
     * Head class.
     *
     * Contains the header for this message.
     */
    @Generated("org.jsonschema2pojo")
    public class Head
    {

        @SerializedName("vid")
        @Expose
        private Integer vid;
        @SerializedName("dt")
        @Expose
        private String dt;
        @SerializedName("lat")
        @Expose
        private Float lat;
        @SerializedName("lon")
        @Expose
        private Float lon;
        @SerializedName("sog")
        @Expose
        private Integer sog;
        @SerializedName("cog")
        @Expose
        private Float cog;
        @SerializedName("sta")
        @Expose
        private Integer sta;

        /**
         * No args constructor for use in serialisation
         */
        public Head()
        {
        }

        /**
         * @param vid Vessel identification number.
         * @param dt Date and time.
         * @param lat Latitude.
         * @param lon Longitude.
         * @param sog Speed over ground.
         * @param cog Course over ground.
         * @param sta Status flags. 32 bit integer where bits one to eight
         * indicate the status of the Dyena box.
         */
        public Head(Integer vid, String dt, Float lat, Float lon, Integer sog, Float cog, Integer sta)
        {
            this.vid = vid;
            this.dt = dt;
            this.lat = lat;
            this.lon = lon;
            this.sog = sog;
            this.cog = cog;
            this.sta = sta;
        }

        /**
         * Get the vessel identification number.
         *
         * @return The vid (vessel identification) number.
         */
        public Integer getVid()
        {
            return vid;
        }

        /**
         * Set the vessel identification number.
         *
         * @param vid The vid (vessel identification) number.
         */
        public void setVid(Integer vid)
        {
            this.vid = vid;
        }

        /**
         * Get the date and time of the message.
         *
         * @return The dt (date and time) of the message.
         */
        public String getDt()
        {
            return dt;
        }

        /**
         * Set the date and time of the message.
         *
         * @param dt The dt (date and time) of the message.
         */
        public void setDt(String dt)
        {
            this.dt = dt;
        }

        /**
         * Get the latitude of the vessel.
         *
         * @return The lat (latitude) of the vessel.
         */
        public Float getLat()
        {
            return lat;
        }

        /**
         * Set the latitude of the vessel.
         *
         * @param lat The lat (latitude) of the vessel.
         */
        public void setLat(Float lat)
        {
            this.lat = lat;
        }

        /**
         * Get the longitude of the vessel.
         *
         * @return The lon (longitude) of the vessel.
         */
        public Float getLon()
        {
            return lon;
        }

        /**
         * Set the longitude of the vessel.
         *
         * @param lon The lon (longitude) of the vessel.
         */
        public void setLon(Float lon)
        {
            this.lon = lon;
        }

        /**
         * Get the speed over ground of the vessel.
         *
         * @return The sog (speed over ground) of the vessel.
         */
        public Integer getSog()
        {
            return sog;
        }

        /**
         * Set the speed over ground of the vessel.
         *
         * @param sog The sog (speed over ground) of the vessel.
         */
        public void setSog(Integer sog)
        {
            this.sog = sog;
        }

        /**
         * Get the course over ground of the vessel.
         *
         * @return The cog (course over ground) of the vessel.
         */
        public Float getCog()
        {
            return cog;
        }

        /**
         * Set the course over ground of the vessel.
         *
         * @param cog The cog (course over ground) of the vessel.
         */
        public void setCog(Float cog)
        {
            this.cog = cog;
        }

        /**
         * Get the status of the system.
         *
         * @return The sta (status) of the system.
         */
        public Integer getSta()
        {
            return sta;
        }

        /**
         * Set the status of the system.
         *
         * @param sta The sta (status) of the system.
         */
        public void setSta(Integer sta)
        {
            this.sta = sta;
        }
    }

    /**
     * Intelligent fender class.
     *
     * Contains intelligent fender data.
     */
    @Generated("org.jsonschema2pojo")
    public class Inf
    {

        @SerializedName("pax")
        @Expose
        private Float pax;
        @SerializedName("pay")
        @Expose
        private Float pay;
        @SerializedName("paz")
        @Expose
        private Float paz;
        @SerializedName("pbx")
        @Expose
        private Float pbx;
        @SerializedName("pby")
        @Expose
        private Float pby;
        @SerializedName("pbz")
        @Expose
        private Float pbz;
        @SerializedName("pcx")
        @Expose
        private Float pcx;
        @SerializedName("pcy")
        @Expose
        private Float pcy;
        @SerializedName("pcz")
        @Expose
        private Float pcz;
        @SerializedName("pdx")
        @Expose
        private Float pdx;
        @SerializedName("pdy")
        @Expose
        private Float pdy;
        @SerializedName("pdz")
        @Expose
        private Float pdz;

        /**
         * No args constructor for use in serialisation
         */
        public Inf()
        {
        }

        /**
         * Intelligent fender individual pin constructor.
         *
         * @param pax Pin "A" X axis
         * @param pay Pin "A" Y axis
         * @param paz Pin "A" Z axis
         * @param pbx Pin "B" X axis
         * @param pby Pin "B" Y axis
         * @param pbz Pin "B" Z axis
         * @param pcx Pin "C" X axis
         * @param pcy Pin "C" Y axis
         * @param pcz Pin "C" Z axis
         * @param pdx Pin "D" X axis
         * @param pdy Pin "D" Y axis
         * @param pdz Pin "D" Z axis
         */
        public Inf(Float pax, Float pay, Float paz, Float pbx, Float pby, Float pbz, Float pcx, Float pcy, Float pcz, Float pdx, Float pdy, Float pdz)
        {
            this.pax = pax;
            this.pay = pay;
            this.paz = paz;
            this.pbx = pbx;
            this.pby = pby;
            this.pbz = pbz;
            this.pcx = pcx;
            this.pcy = pcy;
            this.pcz = pcz;
            this.pdx = pdx;
            this.pdy = pdy;
            this.pdz = pdz;
        }

        /**
         * Intelligent fender array constructor.
         *
         * @param pinData Array of pin data.
         */
        public void setAll(float[] pinData)
        {
            this.pax = pinData[0];
            this.pay = pinData[1];
            this.paz = pinData[2];
            this.pbx = pinData[3];
            this.pby = pinData[4];
            this.pbz = pinData[5];
            this.pcx = pinData[6];
            this.pcy = pinData[7];
            this.pcz = pinData[8];
            this.pdx = pinData[9];
            this.pdy = pinData[10];
            this.pdz = pinData[11];
        }

        /**
         * @return The pax (Pin "A" X axis)
         */
        public Float getPax()
        {
            return pax;
        }

        /**
         * @param pax The pax (Pin "A" X axis)
         */
        public void setPax(Float pax)
        {
            this.pax = pax;
        }

        /**
         * @return The pay (Pin "A" Y axis)
         */
        public Float getPay()
        {
            return pay;
        }

        /**
         * @param pay The pay (Pin "A" Y axis)
         */
        public void setPay(Float pay)
        {
            this.pay = pay;
        }

        /**
         * @return The paz (Pin "A" Z axis)
         */
        public Float getPaz()
        {
            return paz;
        }

        /**
         * @param paz The paz (Pin "A" Z axis)
         */
        public void setPaz(Float paz)
        {
            this.paz = paz;
        }

        /**
         * @return The pbx (Pin "B" X axis)
         */
        public Float getPbx()
        {
            return pbx;
        }

        /**
         * @param pbx The pbx (Pin "B" X axis)
         */
        public void setPbx(Float pbx)
        {
            this.pbx = pbx;
        }

        /**
         * @return The pby (Pin "B" Y axis)
         */
        public Float getPby()
        {
            return pby;
        }

        /**
         * @param pby The pby (Pin "B" Y axis)
         */
        public void setPby(Float pby)
        {
            this.pby = pby;
        }

        /**
         * @return The pbz (Pin "B" Z axis)
         */
        public Float getPbz()
        {
            return pbz;
        }

        /**
         * @param pbz The pbz (Pin "B" Z axis)
         */
        public void setPbz(Float pbz)
        {
            this.pbz = pbz;
        }

        /**
         * @return The pcx (Pin "C" X axis)
         */
        public Float getPcx()
        {
            return pcx;
        }

        /**
         * @param pcx The pcx (Pin "C" X axis)
         */
        public void setPcx(Float pcx)
        {
            this.pcx = pcx;
        }

        /**
         * @return The pcy (Pin "C" Y axis)
         */
        public Float getPcy()
        {
            return pcy;
        }

        /**
         * @param pcy The pcy (Pin "C" Y axis)
         */
        public void setPcy(Float pcy)
        {
            this.pcy = pcy;
        }

        /**
         * @return The pcz (Pin "C" Z axis)
         */
        public Float getPcz()
        {
            return pcz;
        }

        /**
         * @param pcz The pcz (Pin "C" Z axis)
         */
        public void setPcz(Float pcz)
        {
            this.pcz = pcz;
        }

        /**
         * @return The pdx (Pin "D" X axis)
         */
        public Float getPdx()
        {
            return pdx;
        }

        /**
         * @param pdx The pdx (Pin "D" X axis)
         */
        public void setPdx(Float pdx)
        {
            this.pdx = pdx;
        }

        /**
         * @return The pdy (Pin "D" Y axis)
         */
        public Float getPdy()
        {
            return pdy;
        }

        /**
         * @param pdy The pdy (Pin "D" Y axis)
         */
        public void setPdy(Float pdy)
        {
            this.pdy = pdy;
        }

        /**
         * @return The pdz (Pin "D" Z axis)
         */
        public Float getPdz()
        {
            return pdz;
        }

        /**
         * @param pdz The pdz (Pin "D" Z axis)
         */
        public void setPdz(Float pdz)
        {
            this.pdz = pdz;
        }
    }

    /**
     * System class.
     *
     * Contains voltage and temperature information.
     */
    @Generated("org.jsonschema2pojo")
    public class Sys
    {

        @SerializedName("volt")
        @Expose
        private Double volt;
        @SerializedName("temp")
        @Expose
        private Double temp;

        /**
         * No args constructor for use in serialisation
         */
        public Sys()
        {
        }

        /**
         * System constructor.
         *
         * @param volt System voltage.
         * @param temp System temperature.
         */
        public Sys(Double volt, Double temp)
        {
            this.volt = volt;
            this.temp = temp;
        }

        /**
         * Get the system voltage.
         *
         * @return The volt (system voltage).
         */
        public Double getVolt()
        {
            return volt;
        }

        /**
         * Set the system voltage.
         *
         * @param volt The volt (system voltage).
         */
        public void setVolt(Double volt)
        {
            this.volt = volt;
        }

        /**
         * Get the system temperature.
         *
         * @return The temp (system temperature).
         */
        public Double getTemp()
        {
            return temp;
        }

        /**
         * Set the system temperature.
         *
         * @param temp (system temperature).
         */
        public void setTemp(Double temp)
        {
            this.temp = temp;
        }
    }

    /**
     * Vessel motion monitoring system class.
     *
     * Contains information about the motion of the vessel.
     */
    @Generated("org.jsonschema2pojo")
    public class Vmms
    {

        @SerializedName("hve")
        @Expose
        private double[] hve = new double[25];
        @SerializedName("pit")
        @Expose
        private double[] pit = new double[25];
        @SerializedName("rol")
        @Expose
        private double[] rol = new double[25];
        @SerializedName("hed")
        @Expose
        private double[] hed = new double[25];
        @SerializedName("hrms")
        @Expose
        private Double hrms;
        @SerializedName("prms")
        @Expose
        private Double prms;
        @SerializedName("rrms")
        @Expose
        private Double rrms;
        @SerializedName("ax")
        @Expose
        private double[] ax = new double[25];
        @SerializedName("ay")
        @Expose
        private double[] ay = new double[25];
        @SerializedName("az")
        @Expose
        private double[] az = new double[25];

        /**
         * No args constructor for use in serialisation
         */
        public Vmms()
        {
        }

        /**
         * @param hve One seconds worth of heave values (25 in total).
         * @param pit One seconds worth of pitch values (25 in total).
         * @param rol One seconds worth of roll values (25 in total).
         * @param hed One seconds worth of heading values (25 in total).
         * @param hrms Heave RMS (Root Mean Square).
         * @param prms Pitch RMS (Root Mean Square).
         * @param rrms Roll RMS (Root Mean Square).
         * @param ax Vessel acceleration in the X axis.
         * @param ay Vessel acceleration in the Y axis.
         * @param az Vessel acceleration in the Z axis.
         */
        public Vmms(double[] hve, double[] pit, double[] rol, double[] hed, Double hrms, Double prms, Double rrms, double[] ax, double[] ay, double[] az)
        {
            this.hve = hve;
            this.pit = pit;
            this.rol = rol;
            this.hed = hed;
            this.hrms = hrms;
            this.prms = prms;
            this.rrms = rrms;
            this.ax = ax;
            this.ay = ay;
            this.az = az;
        }

        /**
         * @param hve One seconds worth of heave values (25 in total).
         * @param pit One seconds worth of pitch values (25 in total).
         * @param rol One seconds worth of roll values (25 in total).
         * @param hed One seconds worth of heading values (25 in total).
         * @param ax Vessel acceleration in the X axis.
         * @param ay Vessel acceleration in the Y axis.
         * @param az Vessel acceleration in the Z axis.
         */
        public Vmms(double[] hve, double[] pit, double[] rol, double[] hed, double[] ax, double[] ay, double[] az)
        {
            this.hve = hve;
            this.pit = pit;
            this.rol = rol;
            this.hed = hed;
            this.ax = ax;
            this.ay = ay;
            this.az = az;

            double hveCount = 0, pitCount = 0, rolCount = 0;
            for (int i = 0; i < hve.length; i++)
            {
                hveCount += (hve[i] * hve[i]);
                pitCount += (pit[i] * pit[i]);
                rolCount += (rol[i] * rol[i]);
            }
            this.hrms = hveCount / (double) hve.length;
            this.prms = pitCount / (double) pit.length;
            this.rrms = rolCount / (double) rol.length;
        }

        /**
         * Set the heave array.
         *
         * @return The hve (heave) array.
         */
        public double[] getHve()
        {
            return hve;
        }

        /**
         * Get the heave array.
         *
         * @param hve The hve (heave) array.
         */
        public void setHve(double[] hve)
        {
            this.hve = hve;
        }

        /**
         * Get the pitch array.
         *
         * @return The pit (pitch) array.
         */
        public double[] getPit()
        {
            return pit;
        }

        /**
         * Set the pitch array.
         *
         * @param pit The pit (pitch) array.
         */
        public void setPit(double[] pit)
        {
            this.pit = pit;
        }

        /**
         * Get the roll array.
         *
         * @return The rol (roll) array.
         */
        public double[] getRol()
        {
            return rol;
        }

        /**
         * Set the roll array.
         *
         * @param rol The rol (roll) array.
         */
        public void setRol(double[] rol)
        {
            this.rol = rol;
        }

        /**
         * Get the heading array.
         *
         * @return The hed (heading) array.
         */
        public double[] getHed()
        {
            return hed;
        }

        /**
         * Set the heading array.
         *
         * @param hed The hed (heading) array.
         */
        public void setHed(double[] hed)
        {
            this.hed = hed;
        }

        /**
         * Get the heading RMS.
         *
         * @return The hrms (heading RMS).
         */
        public Double getHrms()
        {
            return hrms;
        }

        /**
         * Set the heading RMS.
         *
         * @param hrms The hrms (heading RMS).
         */
        public void setHrms(Double hrms)
        {
            this.hrms = hrms;
        }

        /**
         * Get the pitch RMS.
         *
         * @return The prms (pitch RMS).
         */
        public Double getPrms()
        {
            return prms;
        }

        /**
         * Set the pitch RMS.
         *
         * @param prms The prms (pitch RMS).
         */
        public void setPrms(Double prms)
        {
            this.prms = prms;
        }

        /**
         * Get the roll RMS.
         *
         * @return The rrms (roll RMS).
         */
        public Double getRrms()
        {
            return rrms;
        }

        /**
         * Set the roll RMS.
         *
         * @param rrms The rrms (roll RMS).
         */
        public void setRrms(Double rrms)
        {
            this.rrms = rrms;
        }

        /**
         * Get the X acceleration.
         *
         * @return The ax
         */
        public double[] getAx()
        {
            return ax;
        }

        /**
         * Set the X acceleration.
         *
         * @param ax The ax
         */
        public void setAx(double[] ax)
        {
            this.ax = ax;
        }

        /**
         * Get the Y acceleration.
         *
         * @return The ay
         */
        public double[] getAy()
        {
            return ay;
        }

        /**
         * Set the Y acceleration.
         *
         * @param ay The ay
         */
        public void setAy(double[] ay)
        {
            this.ay = ay;
        }

        /**
         * Get the Z acceleration.
         *
         * @return The az
         */
        public double[] getAz()
        {
            return az;
        }

        /**
         * Set the Z acceleration.
         *
         * @param az The az
         */
        public void setAz(double[] az)
        {
            this.az = az;
        }

        @Override
        public String toString()
        {
            StringBuilder result = new StringBuilder();
            result.append(Arrays.toString(hve));
            return result.toString();
        }
    }

    @Override
    public String toString()
    {
        return "Message{"
                + "bt=" + bt
                + ", head=" + head
                + ", vmms=" + vmms
                + ", inf=" + inf
                + ", eng=" + eng
                + ", sys=" + sys
                + '}';
    }
}
